### ISSUE TITLE
Merge duplicate loading forever

### ISSUE THREAD

**Issue by laisk** [oodesign/merge-duplicate-symbols#84] opened 2020-05-12 18:33 UTC
The window open and it keeps on spinning the loading without any results...
The file is very simple and not connected to a library.

**Comment by oodesign** [comment] 2020-05-13 05:42
Hi @laisk ,

I'm sorry you're having a bad experience with Merge Duplicates...

I'm afraid we're not able to reproduce the issue you describe with our testing set, though. May I ask you for some more details that could help us figure out what the issue may be?

- Even if it's a standalone file (with local symbols and styles), do you have libraries enabled in your Sketch Preferences window? 

- If so, does disabling libraries (uncheck them in the Libraries list in Sketch Preferences) help with the issue?

- Does Merge Duplicates work if you create a brand new file create some dummy duplicate (with the same name) symbols/styles?

- If the previous one works, does Merge Duplicates work if you copy your real file symbols or styles onto the new file, and run the plugin again?

- If still doesn't work, may you try disabling all your other plugins for a moment and try to run Merge Duplicates? You can do so by going to Plugins > Manage plugins, and unchecking them all.

- Can you check if you have missing fonts in your file (you may see a turquoise warning in Sketch top-right corner)? If so, does installing the fonts (or replacing them with the Sketch built-in tool) solve the issue?

- And I know this is the toughest one, but by far the most useful one for us --> May you [send us your Sketch file](mailto:oscar@oodesign.me), or a brand new Sketch file in which you can reproduce the issue so that we can dig a bit deeper? You may replace its real content by dummy stuff, if you wish to. We only need a file in which the issue can be reproduced.

Thanks for reaching out!

**Comment by laisk** [comment] 2020-05-13 11:35
Hi Oscar,
Later I'm going to answer and check all the info, now I'm a bit busy but I
did a video so to show to you what happens and how the file is roughly. Not
sure if it can give all the answers already :)

https://www.dropbox.com/s/l38orxx10xa7axe/MergeDuplicate_IssueEternalLoading.mp4?dl=0

Soon I will get back to you,
Regards,
Laís.

**Comment by laisk** [comment] 2020-05-14 09:26
It's all working back again :)

**Comment by oodesign** [comment] 2020-05-14 11:04
Hi @laisk ,

Wop! Glad that it now works fine for you, but... what did make the difference? 😅

**Comment by laisk** [comment] 2020-05-14 14:15
No idea, as it stoped to work it started back again 🤯

**Comment by oodesign** [comment] 2020-05-14 14:44
Hi @laisk ,

Cool, glad it works again for you!

I'll close the issue then, but please feel free to reopen it (or create another one) if you have any further issues with it.

Thanks!

**Closed by oodesign** 2020-05-14 14:44 UTC
