### ISSUE TITLE
Not able to run plugin

### ISSUE THREAD

**Issue by mchandler11** [oodesign/merge-duplicate-symbols#37] opened 2019-04-25 16:40 UTC
Hey guys,

For the last two weeks, I'm experience issues with this plugin.

1. If I run the plugin at the start of my day, before I do anything else, it works fine when "merging duplicate symbols with the same name all over the document". However, it crashed after I merge the first 4 or 5. 
2. Then, I am not able to even run the option of "merging duplicate symbols with the same name all over the document". My cursor changes to the spinning rainbow wheel and then nothing happens.

I've tried:
- uninstalling all plugins
- reinstalling just this plugin
- restarting sketch
- restarting my computer
- everything!

Super frustrating. Please advise and fix. No, I cannot offer a copy because it is protected under an NDA.

**Comment by mchandler11** [comment] 2019-04-25 16:46
Also. If I try "merging symbols even if name doesn't match", the window appear. I hit "don't merge", and I get the wrong message. It should not have merged....
<img width="651" alt="Screen Shot 2019-04-25 at 12 44 36 PM" src="https://user-images.githubusercontent.com/49992600/56753207-19413e80-6758-11e9-98b2-ced011d177d8.png">

**Comment by oodesign** [comment] 2019-04-25 21:03
Hi @mchandler11,

Sorry to hear that. Which Sketch version and plugin version are you using?

I'm afraid we're not able to reproduce it with our testing set, though.

May you send us a Sketch file with just the symbols that are causing the issue?
You may replace its real content by dummy rectangles, if you wish to. We only need the symbols and its names.

We'll also take a look at that wrong message when you cancel merge and let you know when it's solved.

Thanks!

**Comment by mchandler11** [comment] 2019-04-25 21:12
Thanks, @oodesign.

The thing is, it's a giant design library file with over 450 symbols. I don't know where duplicates are, but I've included a file with just the icons.
[DSL.sketch.zip](https://github.com/oodesign/merge-duplicate-symbols/files/3118886/DSL.sketch.zip)

**Comment by oodesign** [comment] 2019-04-26 08:35
Hi @mchandler11 !

We just released v4.0.4, that solves the messaging issue you addressed. 

Thanks for taking some time to build that file for us to test, but sadly we still cannot reproduce the crashes you are describing (symbols merge properly, merging selected symbols merge properly, ...)

Is there any way that you can figure out which symbols led the plugin to crash when applied to your file? If you are able to do so, can you paste those same symbols to a new file, run the plugin there, and check if it also crashes?

If so, may you please send us that file with just the symbols that are causing the issue?
Again, you may replace its real content by dummy rectangles, if you wish to. We only need the symbols and their names.

Apart, may I also ask you which Sketch version are you using?

Thanks!

**Comment by mchandler11** [comment] 2019-04-26 12:41
Thank, @oodesign.

But, I don't have the bandwidth to go through 450+ symbols and investigate. For future reference, it would be helpful if you guys built a script log that I could just send to you.

Attached is a file with just the symbols. Sketch v.54.1
[ODSM.zip](https://github.com/oodesign/merge-duplicate-symbols/files/3121322/ODSM.zip)

**Comment by mchandler11** [comment] 2019-04-26 12:43
Also, I know there are symbols to merge. Here is what I got just now, before the plugin crashed. 
<img width="847" alt="Screen Shot 2019-04-26 at 8 18 26 AM" src="https://user-images.githubusercontent.com/49992600/56808335-33822780-67ff-11e9-8e6d-1c3f8a05fdb3.png">

**Comment by oodesign** [comment] 2019-04-26 15:03
Hi @mchandler11 ,

We can't see any duplicated symbols in your file, and MergeSelected (or even renaming some to match) and launching MergeDuplicate worked for us...

So here's what I'd suggest: we've built a verbose release (with logs). May you install this version of the plugin, and send us back the logs? You may do that by:

1. **Uninstall** your current version of the "Merge Duplicate Symbols" plugin. 
2. Head to the [release that traces logs](https://github.com/oodesign/merge-duplicate-symbols/releases/tag/4.0.4-logs), and download the Source Code.zip file
3. Unzip it, and double-click on the MergeDuplicateSymbols.sketchplugin to install it.
4. Run it as always on your Sketch design file.
5. Head to **~/Library/Logs/com.bohemiancoding.sketch3/** (you may open a Terminal window, and type "cd ~/Library/Logs/com.bohemiancoding.sketch3/", and then type "open . ")
6. Send us the **Plugin Log.log** file

If you wish to (if you don't like sending us the complete log file), you can delete the Plugin Log.log file prior to running the plugin. Sketch will create it again with just the MergeDuplicateSymbols plugin logs. Or you can send us just our plugin logs. They're easily traceable, because they all start with "MDS -- ".

Hope it helps.

Thanks!

**Comment by oodesign** [comment] 2019-05-02 19:14
Hi @mchandler11,

Did it get any better? Are you still experiencing these issues?

If so, that log would really help us out.
Let us know if there's anything else we can help with.

Thanks!

**Closed** 2019-05-28 17:44 UTC
