### ISSUE TITLE
Merge window does not open

### ISSUE THREAD

**Issue by jjaszkin** [oodesign/merge-duplicate-symbols#82] opened 2020-04-30 11:33 UTC
Hello!
I am very dissapointed because the plugin window opened only for entering licence number, and then the plugin does not work.
I've tried to use it on Sketch 64 and 65. 

Thanks for help!

**Comment by oodesign** [comment] 2020-04-30 11:38
Hi @jjaszkin ,

I'm sorry you're having a bad experience with Merge Duplicates...

I'm afraid we're not able to reproduce the issue you describe with our testing set, though. May I ask you for some more details that could help us figure out what the issue may be?

- Even if it's a standalone file (with local symbols and styles), do you have libraries enabled in your Sketch Preferences window? Does disabling them (uncheck them in the Libraries list in Sketch Preferences) help with the issue?

- Does Merge Duplicates work if you create a brand new file create some dummy duplicate (with the same name) styles?

- If the previous one works, does Merge Duplicates work if you copy your real file symbols or styles onto the new file, and run the plugin again?

- If still doesn't work, may you try disabling all your other plugins for a moment and try to run Merge Duplicates? You can do so by going to Plugins > Manage plugins, and unchecking them all.

- Can you check if you have missing fonts in your file (you may see a turquoise warning in Sketch top-right corner)? If so, does installing the fonts (or replacing them with the Sketch built-in tool) solve the issue?

- And I know this is the toughest one, but by far the most useful one for us --> May you send us a Sketch file, or a brand new Sketch file with just the symbols or styles that are causing the issue so that we can dig a bit deeper? You may replace its real content by dummy stuff, if you wish to. We only need a file in which the issue can be reproduced.

Thanks for reaching out!

**Comment by jjaszkin** [comment] 2020-04-30 12:23
1. the file is opened with Abstract
2. it does works on a new file created directly in Sketch (not from Abstract)
3. it works when copied into new file
4. - 
5. no missing fonts
6. The file is a large internal design system with multiple external libraries (symbols, text and layer styles) so I will send it only when everything else fails :D 
In the same file exported outside Abstract the MergeDuplicates also does not work.

But what is interesting, the MergeDuplicates Classic works fine on the Abstract-opened file

**Comment by oodesign** [comment] 2020-05-04 06:01
Hi @jjaszkin ,

Thank you for the details!
We're investigating some scenarios that could lead to the issue you describe.

I'll make sure to let you know when we're able to release a fix for them.

Thanks!

**Comment by oodesign** [comment] 2020-05-12 10:10
Hi @jjaszkin ,

I'm afraid we still can't reproduce the issue you describe. May I ask you for some more detail?

Abstract automatically changes your Sketch active libraries (based on what you defined as linked libraries in the Abstract project). If you open your design file with Abstract, you should still be able to go to Sketch > Preferences, and see which libraries are active.

Does disabling all the libraries manually (uncheck them) help solve the issue?

If so, may you please send us the linked libraries and a design file you're able to reproduce the issue with?

Also, does disabling all of your other plugins help to run Merge Duplicates without issues? You can do so by going to Plugins > Manage plugins, and unchecking them all.

Thanks a lot for your help!

**Comment by oodesign** [comment] 2020-05-17 10:17
Hi @jjaszkin ,

We just released Merge Duplicates v6.2.1 (the plugin should auto-update), which the ability to log the Merge Duplicates processing details.

Regarding your issue, I'd like to ask you to do the following:

1. Make sure you update to Merge Duplicates v6.2.1
2. Quit Sketch
3. Open Sketch again, and open the file you're having issues with
4. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
5. Run the Merge Duplicates command you were having issues with (I believe it was Merge Duplicate Text Styles and Merge Text Styles from list)
6. Proceed as usual until you experience the issue you described. Don't quit Sketch yet (this is important, as Sketch logs are deleted when you quit the app).
7. Logs will be stored by this point. May you please send us your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by oodesign** [comment] 2020-05-19 08:37
Hi @jjaszkin ,

We just released v6.2.2, which should hopefully fix the issue you described. May you please give it a try and let us know how it worked for you?

Thanks!

**Comment by oodesign** [comment] 2020-05-22 05:01
Hi!

I'm closing the issue as it seems to be fixed, but please feel free to reopen it otherwise, or if you have further issues about it :) 

Thanks!

**Closed by oodesign** 2020-05-22 05:01 UTC

**Comment by jjaszkin** [comment] 2020-05-22 07:07
Hello!

After update everything works fine! :)


Best regards,
Jakub Jaszkin
