### ISSUE TITLE
Unable to merge duplicate text styles

### ISSUE THREAD

**Issue by wvaughan** [oodesign/merge-duplicate-symbols#83] opened 2020-05-01 15:37 UTC
I'm unable to merge text styles by name or by choosing them from the list option. In both cases the modal for merging doesn't appear.

**Comment by wvaughan** [comment] 2020-05-01 15:45
Even if it's a standalone file (with local symbols and styles), do you have libraries enabled in your Sketch Preferences window? Does disabling them (uncheck them in the Libraries list in Sketch Preferences) help with the issue?
- all libraries are disabled

Does Merge Duplicates work if you create a brand new file create some dummy duplicate (with the same name) styles?
- no

If the previous one works, does Merge Duplicates work if you copy your real file symbols or styles onto the new file, and run the plugin again?

If still doesn't work, may you try disabling all your other plugins for a moment and try to run Merge Duplicates? You can do so by going to Plugins > Manage plugins, and unchecking them all.
- yes issue persists

Can you check if you have missing fonts in your file (you may see a turquoise warning in Sketch top-right corner)? If so, does installing the fonts (or replacing them with the Sketch built-in tool) solve the issue?
- no missing fonts

And I know this is the toughest one, but by far the most useful one for us --> May you send us a Sketch file, or a brand new Sketch file with just the symbols or styles that are causing the issue so that we can dig a bit deeper? You may replace its real content by dummy stuff, if you wish to. We only need a file in which the issue can be reproduced.
- yes I can send a sample file

**Comment by oodesign** [comment] 2020-05-02 06:02
Hi @wvaughan ,

Thanks for the details! May I also ask which MacOS, Sketch, and MergeDuplicates versions are you using?

You can send us your design files directly [to our inbox](mailto:oscar@oodesign.me).

Thank you!

**Comment by wvaughan** [comment] 2020-05-11 21:14
Just sent the email with the file.

I'm on MacOS 10.14.6, Sketch 64, and MergeDuplicates 6.0.16

Thanks!

**Comment by oodesign** [comment] 2020-05-12 10:06
Hi @wvaughan ,

I'm afraid we still can't reproduce the issue with the file you sent us and the same scenario (Mojave 10.14.6, Sketch64, and MergeDuplicates6.0.16).

If it still doesn't work for you, does disabling all of your other plugins help to run Merge Duplicates without issues? You can do so by going to Plugins > Manage plugins, and unchecking them all.

Thanks!

**Comment by wvaughan** [comment] 2020-05-12 15:29
Hi,

I've tried disabling all plugins and libraries and am still having the
issue unfortunately.

**Comment by oodesign** [comment] 2020-05-12 15:39
Hi @wvaughan ,

Let me continue this conversation in a separate e-mail thread.
I'll make sure to update this thread when we reach a conclusion.

Thanks!

**Comment by oodesign** [comment] 2020-05-19 18:07
Hi!

A fix for this issue was introduced in v6.2.2.

Thank you!

**Closed by oodesign** 2020-05-19 18:07 UTC
