### ISSUE TITLE
"Merge symbols with the same name" stopped working

### ISSUE THREAD

**Issue by Bequiagal** [oodesign/merge-duplicate-symbols#104] opened 2020-09-28 01:42 UTC
"Merge symbols with the same name" stopped working. To troubleshoot, I copied a symbol from one library into another. The name stayed the same. I ran "Merge symbols with the same name" with the settings set to "Include libraries by default"

It finds the duplicates and reports back the list. 
I selected the duplicate that I wanted and then selected "Merge Duplicates" button at the bottom right. 

I get the feedback"
"Hey Ho! You just removed 0 symbols! Amazing!"

Nothing gets merged. 

This used to work. I am not sure why it stopped working. 

ideas?

I have turned off other plugins to make sure that there were no plugin conflicts. 
My SKETCH is the latest 68.2 and the Merge-duplicate-symbols plugin is up to date (6.4.2) and licensed.

**Comment by jamessimo** [comment] 2020-09-28 06:59
Its not working for me either. I have emailed the Dev and sent my log. 

In addition, I am on version 67.2

**Comment by oodesign** [comment] 2020-09-28 09:55
Hi @Bequiagal ,

Sorry to hear that :(
I'm afraid we cannot reproduce the issue you describe with our testing set, though. 

May I ask you for some further detail?
- Which MacOS version, Sketch version, and MergeDuplicates version are you running?
- Are you having this issue with just one design file, or does it also occur on others, a blank new document, ...?
- Even if it's a standalone file (with local symbols and styles), do you have libraries enabled in your Sketch Preferences window? Does disabling them (uncheck them in the Libraries list in Sketch Preferences) help with the issue?

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please send us your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by Bequiagal** [comment] 2020-09-28 12:44
Thank you Oscar Oto- I’ve attached my plugin Log.log file and will work my way through the rest of your requests and get back to you within a few hours.

Susy


--
Susy Mason
Senior UX  and Digital Designer

University of Vermont
University Communications
Johnson House
617 Main Street
Burlington, VT 05401

T: 802-656-7883

Visit our Drupal Web Guide for documentation and to learn about joining us in help hours for personal support.<http://www.uvm.edu/drupalwebguide>

**Comment by oodesign** [comment] 2020-09-28 13:29
Hi @Bequiagal ,

I'm afraid attachments don't make it into the GitHub issue when they're sent via mail.
Could you please add them directly here? Or [send them to us](mailto:oscar@oodesign.me) via mail?

Thanks!

**Comment by oodesign** [comment] 2020-09-28 15:21
Hi @Bequiagal ,

Thanks for sending us the logs. 
We don't see any issue occurring in the merge process, though, and still can't reproduce the issue you describe. 🤔

On our end, the only situation that can lead to a "You removed 0 symbols" is that the symbols replaced didn't exist in the local Sketch file, but were already instances of symbols of another library. Something like:

- **LibraryA**.sketch has a symbol called **Symbol1**
- **LibraryB**.sketch has a symbol called **Symbol1**
- **LocalFile**.sketch, that uses LibraryA and LibraryB as linked libraries, uses the Symbol1 (let's say from LibraryA)

In the above situation, Merge Duplicates would find the duplicates (there is a Symbol1 defined in two linked libraries), and prompt you which of them you want to use. For the sake of the example, let's say you choose to use the one in **LibraryB**.

The plugin should now replace all the Symbol1 instances (coming from LibraryA) for the one in LibraryB. Note that the "Symbol1" never existed in the local (LocalFile.sketch) file, so... it can't be removed (and that's why you get a "0 symbols removed" message).

May that be your case?

Otherwise, could you please describe thoroughly your scenario, and [send us](mailto:oscar@oodesign.me) a set of Sketch files you can actually reproduce the issue with?

Thank you!

**Comment by Bequiagal** [comment] 2020-09-28 21:11
Oscar
In your example below if I follow you correctly, the LocalFile.sketch file which has an instance of Symbol1 from LibraryA would change to the Symbol1 used in LibraryB after the Merge Duplicate Symbol operation is complete.

Correct?

--
Susy Mason
Senior UX  and Digital Designer

University of Vermont
University Communications
Johnson House
617 Main Street
Burlington, VT 05401

T: 802-656-7883

Visit our Drupal Web Guide for documentation and to learn about joining us in help hours for personal support.<http://www.uvm.edu/drupalwebguide>

**Comment by oodesign** [comment] 2020-09-28 21:16
Hi!

Merge Duplicates doesn't affect the libraries (unless you're triggering it from a library, obviously).

In the example above, it would replace all instances of LibraryA/Symbol1 in LocalFile.sketch for LibraryB/Symbol1 ones. And it wouldn't remove anything from anywhere, as the conflict was coming from the libraries, and there was no "Symbol1" in the local file.

**Comment by Bequiagal** [comment] 2020-09-28 21:18
But everything that was linked to Symbol1 in document A would trigger a “LIBRARY UPDATE”- yes? As Symbol1 in document A was merged with Symbol1 in document



--
Susy Mason
Senior UX  and Digital Designer

University of Vermont
University Communications
Johnson House
617 Main Street
Burlington, VT 05401

T: 802-656-7883

Visit our Drupal Web Guide for documentation and to learn about joining us in help hours for personal support.<http://www.uvm.edu/drupalwebguide>

**Comment by oodesign** [comment] 2020-09-28 21:28
I'm not sure what you mean about triggering a "library update".

If Merge Duplicates is triggered on the LocalFile.sketch, the only file that gets affected is LocalFile.sketch. The libraries are not affected at all (and both Symbol1 continue to exist on both LibraryA and LibraryB).

In the described scenario, rather than "merging" duplicates, what you'd be doing is "Choosing which 'Symbol1' (from the available libraries) you want to use".

**Comment by Bequiagal** [comment] 2020-09-28 21:30
I am going to go back and read this again…HaHa it’s starting to feel like those match problems with trains… You know, like this:

Train A, traveling 40 mph, leaves Westford heading toward Eastford, 260 miles away. One hour after Train A leaves Westford, Train B, traveling 70 mph, leaves Eastford heading toward Westford. When do the two trains meet? Notice that in this problem, the two trains do not leave their respective cities at the same time.


--
Susy Mason
Senior UX  and Digital Designer

University of Vermont
University Communications
Johnson House
617 Main Street
Burlington, VT 05401

T: 802-656-7883

Visit our Drupal Web Guide for documentation and to learn about joining us in help hours for personal support.<http://www.uvm.edu/drupalwebguide>

**Comment by Bequiagal** [comment] 2020-09-28 22:17
This makes total sense Oscar and I recreated your test in a new file with the libraries and it worked as you described.

When I merge 2 symbols in the same library, the reject is removed and the selected one stays.

I was looking to do the same thing across libraries.

So all type styles are referenced in the Typography library
And all icons are referenced in the Icon library etc. and any duplicates across different libraries would be removed upon merge.


--
Susy Mason
Senior UX  and Digital Designer

University of Vermont
University Communications
Johnson House
617 Main Street
Burlington, VT 05401

T: 802-656-7883

Visit our Drupal Web Guide for documentation and to learn about joining us in help hours for personal support.<http://www.uvm.edu/drupalwebguide>

**Comment by oodesign** [comment] 2020-09-29 08:28
Hi!

Merge Duplicates is, per design, not able to "edit" the linked libraries.

The reasoning below it is that it could be extremely risky to do so, as using Merge Duplicates in a child document could edit and remove symbols/styles from, say, your company design system (and could even go unnoticed).

So I'm afraid we won't be adding that feature...

**Comment by Bequiagal** [comment] 2020-09-29 13:03
Oscar

Thank you for this plugin and thank you for your support.

I believe I had a misunderstanding of the functionality.

I merged duplicates and then was able to remove the unwanted library symbol/layer style/text styles selectively that no longer had other things linking to them.

Oscar, is there a way to keep the list open when you “Merge duplicates by list” the way you can when you “Merge duplicates with the same name”?

Susy


--
Susy Mason
Senior UX  and Digital Designer

University of Vermont
University Communications
Johnson House
617 Main Street
Burlington, VT 05401

T: 802-656-7883

Visit our Drupal Web Guide for documentation and to learn about joining us in help hours for personal support.<http://www.uvm.edu/drupalwebguide>

**Comment by oodesign** [comment] 2020-09-30 09:54
Hi!

No worries. We could do better at messaging, when dealing with these cases where you "choose" from library, instead of merging. So that's already great feedback, thank you!

I'm not sure what you mean by "keeping the list open". Could you attach some screenshots to illustrate?

Thanks!

**Comment by Bequiagal** [comment] 2020-09-30 13:11
Oscar
I just made you a video that demonstrates my experience of the differences between “Merge from list” and “merge with the same name”

Also—“Merge with the same name” is not working at all for Layer Styles- Lots of duplicates show up in the list view but not in the “with same name view”

https://youtu.be/L8o_fyp41g4

• Merge Duplicates with the same name Allows you to continue working with the same list and making selections for sets of duplicates to merge, and

• Merge Duplicates from List Only allows you to merge one set of duplicates at a time, requiring you to keep going back into the list over and over again to make your "Merge" selection.

--
Susy Mason
Senior UX  and Digital Designer

University of Vermont
University Communications
Johnson House
617 Main Street
Burlington, VT 05401

T: 802-656-7883

Visit our Drupal Web Guide for documentation and to learn about joining us in help hours for personal support.<http://www.uvm.edu/drupalwebguide>

**Comment by oodesign** [comment] 2020-09-30 13:24
Hi!

Thanks for arranging a video capture. I'm afraid the Youtube video is set as Private, though, and we cannot get to see it 😅. Can you change its permission setting? Otherwise I'd suggest platforms like [Streamable](https://streamable.com/) to share it quickly & free.

Regarding the issue about some duplicate layer styles not showing in the "Merge duplicate layer styles (with the same name)" option, could you please [create a separate issue](https://github.com/oodesign/merge-duplicate-symbols/issues/new/choose) in GitHub to address it? Thanks!

And regarding your last point, as far as I understand you'd like to be able to do several "different merges" in a row without closing the window, isn't it? Something like...?

- Choose StyleA, StyleB and StyleC, and merge them
- And, without closing the window, clear the list, choose StyleD, StyleE and StyleF, and merge them.

**Comment by Bequiagal** [comment] 2020-09-30 13:27
I have made it public for you.

I will take it down after you look at it as I am not going to caption it… you don’t need captions, right?

Susy
https://youtu.be/L8o_fyp41g4


--
Susy Mason
Senior UX  and Digital Designer

University of Vermont
University Communications
Johnson House
617 Main Street
Burlington, VT 05401

T: 802-656-7883

Visit our Drupal Web Guide for documentation and to learn about joining us in help hours for personal support.<http://www.uvm.edu/drupalwebguide>

**Comment by oodesign** [comment] 2020-09-30 13:53
Got it! 

First of all, thank you for arranging that capture! it is really awesome! 🤩

The "Merge from list" option was designed to address very specific merges, for scenarios typically involving styles named differently. Like a "merge selected styles" option. 

I see the point (and the benefit) of being able to do several "merge from list" in a row (one after another), though, so I'll make sure to add it to our backlog to analyze.

I've added [a new issue](https://github.com/oodesign/merge-duplicate-symbols/issues/105) on your behalf to address this. I'll also be happy to keep you updated on it.

---

Regarding the "Merge duplicate layer styles (with the same name)", it should do exactly what you describe. Detect all duplicate (by name) layer styles, and prompt you what to do with each of them, exactly the same way as the "Merge Duplicate Symbols" behaves.

I see in the recording that the "Merge layer styles (with the same name)" is not working for you (as it seems it doesn't open the merge window. May I ask...

1. While in the Sketch file, can you press F3 to show all the active windows? Sometimes the "Merge duplicates" window is actually open, but it gets behind the Sketch app. If so, clicking on it should bring it to front.
2. Otherwise, may you send us you plugin logs when triggering "Merge layer styles (with the same name)"?

I guess you're already familiar with the log process, but just in case, you can do so by:


1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please send us your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Comment by Bequiagal** [comment] 2020-09-30 17:25
I would like to know why “Merge Symbols with the Same Name” is not returning anything at all. (this is shown about 1:43 in the video)

Outside of that, yes please! Keep me on your list to get updated when the plugin is updated with a new feature.

--
Susy Mason
Senior UX  and Digital Designer

University of Vermont
University Communications
Johnson House
617 Main Street
Burlington, VT 05401

T: 802-656-7883

Visit our Drupal Web Guide for documentation and to learn about joining us in help hours for personal support.<http://www.uvm.edu/drupalwebguide>

**Comment by oodesign** [comment] 2020-09-30 21:25
The "Merge symbols with the same name" does seem to work (it's the one you reference to explain how this type of layout enables you to do multiple merges using the same window).

The one that doesn't seem to appear is the "Merge layer styles (with the same name)", while it should. The second part of the previous reply was trying to address that issue. 

May I ask you to check the first option (F3 to see if there's already an active Merge Layer styles window), or send us the logs when triggering "Merge duplicate layer styles (with the same name)"? 

Thanks!

**Comment by Bequiagal** [comment] 2020-10-13 20:08
Thank you for your help Oscar.


--
Susy Mason
Senior UX  and Digital Designer

University of Vermont
University Communications
Johnson House
617 Main Street
Burlington, VT 05401

T: 802-656-7883

Visit our Drupal Web Guide for documentation and to learn about joining us in help hours for personal support.<http://www.uvm.edu/drupalwebguide>

**Closed** 2020-10-13 20:07 UTC

**Comment by oodesign** [comment] 2020-10-13 20:11
I was typing the reply, but you were faster than me 😅

I'm closing this issue as the main topic got addressed. But please feel free to reopen it (or to create a new one) if you have further questions or concerns about it.

Thanks!
