### ISSUE TITLE
Unable to merge with the same names. Sketch version 65.1 

### ISSUE THREAD

**Issue by mantasster** [oodesign/merge-duplicate-symbols#85] opened 2020-05-13 06:32 UTC
Hi.
Our company just bought  Merge-dublicate. It works fine in manual mode (merge selected symbols, etc.) But it does nothing when pressing e.g. "Merge symbols with the same names" - even though I see some symbols with exactly same name.
What should I do? Would be great to use this feature - that's why we bought this software :)

**Comment by oodesign** [comment] 2020-05-13 07:27
Hi @mantasster ,

I'm sorry you're having a bad experience with Merge Duplicates...

I'm afraid we're not able to reproduce the issue you describe with our testing set, though. May I ask you for some more details that could help us figure out what the issue may be?

- Which MacOS version and Merge Duplicates version are you using?

- Even if it's a standalone file (with local symbols and styles), do you have libraries enabled in your Sketch Preferences window?

- If so, does disabling libraries (uncheck them in the Libraries list in Sketch Preferences) help with the issue?

- Does Merge Duplicates work if you create a brand new file create some dummy duplicate (with the same name) symbols/styles?

- If the previous one works, does Merge Duplicates work if you copy your real file symbols or styles onto the new file, and run the plugin again?

- If still doesn't work, may you try disabling all your other plugins for a moment and try to run Merge Duplicates? You can do so by going to Plugins > Manage plugins, and unchecking them all.

- Can you check if you have missing fonts in your file (you may see a turquoise warning in Sketch top-right corner)? If so, does installing the fonts (or replacing them with the Sketch built-in tool) solve the issue?

- And I know this is the toughest one, but by far the most useful one for us --> May you [send us your Sketch file](mailto:oscar@oodesign.me), or a brand new Sketch file in which you can reproduce the issue so that we can dig a bit deeper? You may replace its real content by dummy stuff, if you wish to. We only need a file in which the issue can be reproduced.

Thanks for reaching out!

**Comment by mantasster** [comment] 2020-05-13 09:09
Hi!

- Which MacOS version and Merge Duplicates version are you using?
- MacOS Catalina 10.15.3 (19D76)

- Even if it's a standalone file (with local symbols and styles), do you have libraries enabled in your Sketch Preferences window?
- Yes

- If so, does disabling libraries (uncheck them in the Libraries list in Sketch Preferences) help with the issue?
- No, it doesn't work...

- Does Merge Duplicates work if you create a brand new file create some dummy duplicate (with the same name) symbols/styles?
- No, it doesn't work either...

- If still doesn't work, may you try disabling all your other plugins for a moment and try to run Merge Duplicates? You can do so by going to Plugins > Manage plugins, and unchecking them all.
- Doesn't help :(

- Can you check if you have missing fonts in your file (you may see a turquoise warning in Sketch top-right corner)? If so, does installing the fonts (or replacing them with the Sketch built-in tool) solve the issue?
- Doesn't help :(


- And I know this is the toughest one, but by far the most useful one for us --> May you send us your Sketch file, or a brand new Sketch file in which you can reproduce the issue so that we can dig a bit deeper? You may replace its real content by dummy stuff, if you wish to. We only need a file in which the issue can be reproduced.
- Sure, I am sending dummy file which don't work.

Cheers!

**Comment by oodesign** [comment] 2020-05-13 09:40
Hi @mantasster ,

I'm afraid we're still not able to reproduce it. You may check the plugin behavior on https://imgur.com/a/XipN7K1 .

Which version of Merge Duplicates are you using (should be 6.0.17 by now)?

We're working on a log verbose version of Merge Duplicates, that will be released by the end of this week, and that hopefully will help us investigate further issues likes the one you describe.

If you're willing to, once it's available I'd ask you to install it and try to run Merge Duplicate Symbols again, and send us the logs. Logs don't contain any sensitive information about your design file, it's just plugin processing related information.

I'll be happy to let you know here when the logging version is available.

Thanks for your help!

**Comment by mantasster** [comment] 2020-05-14 09:14
Hi @oodesign  - I see it works well for you.
I am using v. 6.0.17 :)
I'll try to reinstall add-on and perform other things - it is highly needed function.
Inform me about logging version. Thanks.

**Comment by oodesign** [comment] 2020-05-14 11:10
Hi @mantasster ,

Absolutely, I'll make sure to let you know when it's available.
Really looking forward to find the cause of the issue :)

**Comment by mantasster** [comment] 2020-05-15 14:14
@oodesign It works! I just opened Sketch today and it started working. Thanks :)

**Comment by oodesign** [comment] 2020-05-15 14:18
Wop! 

Glad it works for you! But... what did make the difference? 😅
Actually yesterday we closed [an issue](https://github.com/oodesign/merge-duplicate-symbols/issues/84) that also suddenly started working back again... 

Any clue? Did you restart (Sketch or MacOS), update, uninstall anything, disabled a plugin, remove libraries... ?

Anyway, thanks for letting us know! And happy it now works for you ☺️

**Comment by oodesign** [comment] 2020-05-17 10:15
Hi!

I'm closing this issue as it seems to work back for you. Anyway, please feel free to reopen it (or create a new one) if you continue to have issues with the plugin.

Thanks a lot!

**Closed by oodesign** 2020-05-17 10:15 UTC
