### ISSUE TITLE
Merging Some Layer Styles Not Working

### ISSUE THREAD

**Issue by chelseastudenski** [oodesign/merge-duplicate-symbols#52] opened 2019-07-01 15:51 UTC
I have two sets of layer styles for our brand colors: Fills and Outlines
I was able to merge the two fills layer styles that I need to, but when I try to do the same with the outline versions I am seeing the issue in the below screenshot. This bug ultimately blocks me from being able to merge them. 

<img width="716" alt="Screen Shot 2019-07-01 at 10 43 00 AM" src="https://user-images.githubusercontent.com/42183866/60449536-83111500-9bed-11e9-85de-feb6118eaf15.png">

**Comment by oodesign** [comment] 2019-07-01 16:00
Hi @chelseastudenski ,

Sorry to hear that! Looks like a bug generating the previews,  but we're not able to reproduce it with our testing set.

May you please send us your design files and related external libraries? You may do so here or send us a mail to to oscar@oodesign.me with the files or links to download them.

Thanks!

**Comment by oodesign** [comment] 2019-07-02 06:37
Hi @chelseastudenski ,

Thanks for sending us those files. It really helped a lot!

I see you're using an older version of Merge Duplicates. The issue you're describing should be fixed in the current version (v5.0.2). May you install the new one and run the plugin again? We tested it on your files and seems to work fine, but please let us know if it worked well for you.

You can find the download link in the mail or receipt you got from Gumroad.
Anyway, if you go to [http://gumroad.com/library](http://gumroad.com/library) (and log in with the account you used to purchase the plugin) you may find all your purchases there. Click on the "Merge duplicates" one and you will find a direct download button there.

What you'll get is a zipped file. Unzip it and double click on the .sketchplugin file to install it. 
If you had a previous version installed you will be prompted to replace it for the new version (v5.0.2) or keep the old one. Press **Replace** to install the new one. And... you're ready to go!

Otherwise you can click on "Manage plugins" inside Sketch, right click on the "Merge Duplicates" one and Uninstall it. Then install it again by double clicking on the .sketchplugin file you just downloaded from Gumroad.

Hope it helps!

**Comment by chelseastudenski** [comment] 2019-07-02 16:49
Thank you for your help. That solved the issue for me.

How will I know when plugin updates are available in the future? Most just show up within Sketch.

Chelsea
________________________________

**Comment by oodesign** [comment] 2019-07-02 20:47
Hi @chelseastudenski !

Happy it worked for you!

We'll keep updating the plugin with new features and some cool things, but now that it's not a free plugin anymore we're not able to use the Sketch built in auto-update feature, and therefore you won't get notified directly in Sketch.

We will use the same e-mail account you used to purchase the plugin to let you know when an update gets released, and you'll be able to download it from your Gumroad account products page. We won't use your e-mail for any other purpose.

It's obviously not ideal, so sorry for any inconvenience this may cause. We're trying to figure out a smoother approach :)

Thanks for getting in touch!

**Closed** 2019-07-03 11:01 UTC
