### ISSUE TITLE
Layers/Symbols/Fonts that are overridden detach from layer/text style instead of being replaced.

### ISSUE THREAD

**Issue by andrewdaniels** [oodesign/merge-duplicate-symbols#107] opened 2020-10-02 13:49 UTC
I love the Merge Duplicate tool, my team works on a lot of projects and any time we Carry over anything from another file it clutters us with more text styles, layer styles or symbols needed.

But recently when I have merged duplicates, **my overridden styles/symbols have just detached instead of being replaced.** This is frustrating because the point of this plugin is that it isn't destructive. This forces me to have to go to every place that layer style was used and assign a new layer style. This is a huge problem for me right now.

**Comment by oodesign** [comment] 2020-10-02 13:59
Hi @andrewdaniels ,

I'm sorry you're having issues with Merge Duplicates. 😔

The plugin is not supposed to detach any symbol or style (just replace them by the one that got selected).

The only scenario where a detachment could happen is when you run Merge Duplicates on a library file (and merge some symbols and styles), and there were other "child" Sketch files using that library' symbols and styles that now don't exist anymore (because they got merged). Something like:

1. **LocalFile.sketch** uses **SymbolA** and **SymbolB** from **LibraryFile.sketch**.
2. You run Merge Duplicates in **LibraryFile.sketch**, and decide to merge SymbolA and SymbolB (and **the chosen one is SymbolB**).
3. Now **every instance of SymbolA in the LocalFile.sketch** is detached, as the original symbol doesn't exist anymore.

May that be the case?

Otherwise, could you give us some further detail about your scenario?

**Comment by oodesign** [comment] 2020-10-13 08:10
Hi @andrewdaniels ,

Are you still experiencing this issue?

Thanks!

**Comment by andrewdaniels** [comment] 2020-10-13 14:42
@oodesign So when merging I did uncheck the "Include all enabled library symbols".. And it did help mitigate the problem, but it didn't really help me clean up the document in regards to my layer styles at least.

I haven't had the obvious problem of all my layer styles being detached.... But is there a way to fix that problem? With libraries?? It would be super nice, Ik it is probably harder then a few lines of code.

**Comment by oodesign** [comment] 2020-10-13 20:06
Hi @andrewdaniels ,

Sorry to hear that :(
I'm afraid we cannot reproduce the issue you describe with our testing set, though. 

To investigate a bit further your issue, may you please send us the Merge Duplicates logs? Logs don't contain any sensitive information about your design file, it's just plugin processing related information. You can do so by:

1. Quit Sketch
2. Open Sketch again, and open the file you're having issues with
3. Merge Duplicates logs are disabled by default. You may enable them by going to Plugins > Merge duplicates... > Settings , and switching on the logging ability.
4. Run the Merge Duplicates command you were having issues with (Merge Symbols, Merge Text Styles or Merge Layer Styles, or any of their variants)
5. Proceed as usual until you experience the issue you described. **Don't quit Sketch yet** (this is important, as Sketch logs are deleted when you quit the app).
6. Logs will be stored by this point. May you please [send us](mailto:oscar@oodesign.me) your log file so that we can investigate what may be causing the issue? You may find them in ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log

Thanks a lot for your help! 🥰

**Closed** 2020-10-27 09:22 UTC
